### ISSUE TITLE
Roadmap v1.0

### ISSUE THREAD

**Issue by TulioAbreu** [TulioAbreu/shazow-bot#30]
## Roadmap

- [ ] Design 
    - [ ] Landing page
    - [ ] Login
    - [ ] Page for listing common commands (including admin commands)
    - [ ] Page for listing server commands (if user is authenticated and is admin/mod, he should be able to edit, add or remove commands)
- [ ] Webpage
    - [ ] Frontend
        - [ ] Implement landing page
        - [ ] Implement login page
        - [ ] Implement page for listing common commands
        - [ ] Implement page for listing server commands
    - [ ] Backend
        - [ ] Authentication
        - [ ] List commands
        - [ ] Add commands
        - [ ] Edit commands
        - [ ] Remove commands
